### ISSUE TITLE
Wont work, help, im an idiot

### ISSUE THREAD

**Issue by Bendilin** [FFG-Blinkenn/RPEssentials#1]
I just downloaded this and tried it into my modules, addons, and the server folder, but it never works, please help this confused human who doesnt know anything.

**Comment by FFG-Blinkenn** [comment]
Manually put the from "RPEssentials-master.zip\RPEssentials-master\addons\darkrpmodification\lua\darkrp_modules" in the darkrp modules and put lua file into an addons folder.

**Comment by Bendilin** [comment]
The server addons folder or your addons folder?

**Comment by FFG-Blinkenn** [comment]
Server

**Comment by Bendilin** [comment]
Do i put the master file anywhere?

**Comment by FFG-Blinkenn** [comment]
Put the master folder in addons, cut the folder in /addons/darkrpmodification/lua/darkrp_modules/ and put it in darkrp_modules

**Comment by Bendilin** [comment]
I put the Lua  under addoms and the darkrp_modules under darkrp_modules but its still not working, i had to rename lua to lua1 so i can put it into the addons
